name: CI-Ubuntu

on: [pull_request]

jobs:
  build:
    name: Build & Test on Ubuntu 22.04
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master'
    strategy:
      matrix:
        php:
          - 8.0
          - 8.1
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y network-manager libnss3-tools jq xsel
          composer install --no-interaction --prefer-dist
      - name: Test
        run: vendor/bin/phpunit
